FROM mongo:7

ENV sourcesdir /go/src/github.com/microservices-demo/user/
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN apt-get update && apt-get install -yq git curl

RUN curl -sSL https://go.dev/dl/go1.22.0.linux-amd64.tar.gz -o go.tar.gz && \
    tar -C /usr/local -xzf go.tar.gz && \
    rm go.tar.gz

COPY . ${sourcesdir}
WORKDIR ${sourcesdir}
RUN go mod download
